# Generated by Django 4.2.6 on 2023-10-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_items_photo"),
    ]

    operations = [
        migrations.RenameField(model_name="items", old_name="title", new_name="name",),
    ]
