# Generated by Django 4.2.6 on 2023-11-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_title_items_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outfits",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("upper_path", models.CharField(max_length=100)),
                ("lower_path", models.CharField(max_length=100)),
                ("foot_path", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="items",
            name="photo",
            field=models.ImageField(blank=True, default="", upload_to="itemimages/"),
        ),
    ]
