# Generated by Django 4.2.6 on 2023-11-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_outfits_alter_items_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outfits", old_name="category", new_name="type",
        ),
    ]
