# Generated by Django 4.2.6 on 2024-02-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_outfits_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfits", name="score", field=models.FloatField(default=0.0),
        ),
    ]
