# Generated by Django 4.2.6 on 2024-02-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_outfits_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="items", name="likes", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="outfits", name="like", field=models.BooleanField(default=False),
        ),
    ]
