# Generated by Django 4.2.6 on 2024-02-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_items_likes_outfits_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfits", name="like", field=models.BooleanField(default=True),
        ),
    ]
