# Generated by Django 4.2.6 on 2024-02-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_outfits_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items", name="price", field=models.CharField(max_length=50),
        ),
    ]
