# Generated by Django 4.2.6 on 2024-02-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_outfits_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfits",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
