# Generated by Django 5.0.2 on 2024-03-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_favorite_colors_userprofile_upper_fav_colors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='outfits',
            old_name='user_id',
            new_name='user',
        ),
    ]
