# Generated by Django 5.0.2 on 2024-03-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_user_id_items_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
