# Generated by Django 5.0.2 on 2024-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_likes_items_like_alter_items_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfits',
            name='foot_color',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outfits',
            name='lower_color',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outfits',
            name='upper_color',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
