# Generated by Django 5.0.2 on 2024-03-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_outfits_foot_color_outfits_lower_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='pattern',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outfits',
            name='upper_pattern',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
