# Generated by Django 5.0.2 on 2024-03-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_items_pattern_outfits_upper_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfits',
            name='foot_color',
        ),
        migrations.RemoveField(
            model_name='outfits',
            name='foot_path',
        ),
        migrations.RemoveField(
            model_name='outfits',
            name='lower_color',
        ),
        migrations.RemoveField(
            model_name='outfits',
            name='lower_path',
        ),
        migrations.RemoveField(
            model_name='outfits',
            name='upper_color',
        ),
        migrations.RemoveField(
            model_name='outfits',
            name='upper_path',
        ),
        migrations.RemoveField(
            model_name='outfits',
            name='upper_pattern',
        ),
        migrations.AddField(
            model_name='outfits',
            name='foot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foot_outfits', to='myapp.items'),
        ),
        migrations.AddField(
            model_name='outfits',
            name='lower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_outfits', to='myapp.items'),
        ),
        migrations.AddField(
            model_name='outfits',
            name='upper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_outfits', to='myapp.items'),
        ),
    ]
