# Generated by Django 5.0.2 on 2024-03-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_outfits_foot_color_remove_outfits_foot_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='item_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='outfit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
