# Generated by Django 5.0.2 on 2024-03-19 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_userprofile_item_time_userprofile_outfit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
