# Generated by Django 5.0.2 on 2024-03-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_outfits_foot_id_alter_outfits_lower_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
